# -*- coding: utf-8 -*-
"""Data Aumentation - aula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eqVPBIu6mQokDtrIabVmDZFldbp3_jh

# Data Augmentation com OpenCV e numpy
"""

from google.colab import drive
drive.mount('/content/drive')

# Bibliotecas
import numpy as np
from skimage import io, img_as_ubyte
from skimage.transform import rotate, AffineTransform, warp
from skimage.util import random_noise
import random
import os
import cv2
import matplotlib.pyplot as plt

# Imagens originais
'''
BD_Oficial = ('/content/drive/MyDrive/ClassifSeg/Augumentation/Aleatorio1')
if os.path.isdir('BD_Oficial') == False:
    print('A pasta "BD_Oficial" não existe. Criando diretório.')
    os.mkdir('/content/drive/MyDrive/ClassifSeg/Augumentation/Aleatorio1')
else:
    print('A pasta "BD_Oficial" existe.')
    images_path = os.getcwd() + '\\BD_Oficial'
# Imagens modificadas
if os.path.isdir('Aumented_Images') == False:
    print('A pasta "Aumented_Images" não existe. Criando diretório.')
    os.mkdir('Aumented_Images')
else:
    print('A pasta "Aumented_Images" existe.')
    augmented_path = os.getcwd() + '\\Aumented_Images'
'''

images_path =  ('/content/drive/MyDrive/ClassifSeg/Augumentation/Aleatorio1')
augmented_path = ('/content/drive/MyDrive/ClassifSeg/Augumentation/Aleatorio1')
# Imagens Originais
images = []
for im in os.listdir(images_path):
    images.append(os.path.join(images_path, im))
    

images_to_generate = 200  # qtd de imagens a serem geradas
i = 1                   # variavel para inteirar no

"""### Funções Transformações Geométricas

1. Rotação Anti-Horária
2. Rotação Horária
3. Flip Horizontal
4. Flip Vertical
5. Ruídos Sal&Pimenta
6. Brilho
7. Median Blur
8. Zoom
"""

def rotacao_anti(image):
    '''
        Função responsável por fazer a rotação anti-horaria da imagem.
        Entrada: Imagem 
        Saída: Imagem rotacionada entre 0 a 180° no 
    '''
    angle = random.randint(0, 180)
    return rotate(image, angle)


def rotacao_horaria(image):
    '''
        Função responsável por fazer a rotação horaria da imagem.
        Entrada: Imagem 
        Saída: Imagem rotacionada entre 0 a 180° no sentindo horario
    '''
    angle = random.randint(0, 180)
    return rotate(image, -angle)


def h_flip(image):
    '''
        Função responsável por fazer a inversão horizontal da imagem.
        Entrada: Imagem 
        Saída: Imagem invertida no sentido horizontal
    '''
    return np.fliplr(image)


def v_flip(image):
    '''
        Função responsável por fazer a inversão vertical da imagem.
        Entrada: Imagem 
        Saída: Imagem invertida no sentido vertical
    '''
    return np.flipud(image)


def ruidos_img(image):
    '''
        Função responsável por inserir ruídos randomincos do tipo sal e pimenta na imagem.
        Entrada: Imagem 
        Saída: Imagem com ruidos do tipo sal e pimenta
    '''
    return random_noise(image)


def brightness(image):
    '''
        Função responsável por incrementar brilho a imagem.
        Entrada: Imagem 
        Saída: Imagem com brilho
    '''
    bright = np.ones(image.shape, dtype="uint8") * 70
    brightincrease = cv2.add(image, bright)

    return brightincrease

def blur_img(image):
    '''
        Função responsável por aplicar um filtro mediana na imagem.
        Entrada: Imagem 
        Saída: Imagem com filtro mediana    
    '''

    k_size = random.randrange(1,10,2)
    img_blur = cv2.medianBlur(image, k_size)
    return img_blur

def zoom(image):
    '''
    Função responsável por aplicar zoom na imagem.
    Entrada: Imagem
    Saída: Imagem com zoom
    '''
    zoom_value = random.random()
    hidth, width = image.shape[:2]
    h_taken = int(zoom_value*hidth)
    w_taken = int(zoom_value*width)
    h_start = random.randint(0, hidth-h_taken)
    w_start = random.randint(0, width-w_taken)
    image = image[h_start:h_start+h_taken, w_start:w_start+w_taken, :]
    image = cv2.resize(image, (hidth, width), cv2.INTER_CUBIC)
    return image

"""### Dicionário com as funções criadas"""

# Dicionario para ativacao das funcoes
transformations = {'Rotacao anti-horaria': rotacao_anti,
                   'Rotacao horaria': rotacao_horaria,
                   'Horizontal flip': h_flip,
                   'Vertical flip': v_flip,
                   'Ruidos': ruidos_img,
                   'Brilho': brightness,
                   'Blur Image': blur_img,
                   'Zoom': zoom
                   }

"""### Criação das imagens"""

while i <= images_to_generate:
    image = random.choice(images)
    original_image = io.imread(image)
    transformed_image = []
#     print(i)
    n = 0       # variável para iterar até o número de transformação 
    # escolha um número aleatório de transformação para aplicar na imagem
    transformation_count = random.randint(1, len(transformations))

    while n <= transformation_count:
        # Escolha aleatorio do metodo a ser aplicado
        key = random.choice(list(transformations))
        print(f'A imagem {i} sofreu as seguintes trasnformações geometricas: {key}')
        transformed_image = transformations[key](original_image)
        n += 1

    new_image_path = "%s/augmented_image_%s.jpg" % (augmented_path, i)
    # Converta uma imagem para o formato de byte sem sinal, com valores em [0, 255].
    transformed_image = img_as_ubyte(transformed_image)
    # converter a imagem antes d egravar
    transformed_image = cv2.cvtColor(transformed_image, cv2.COLOR_BGR2RGB)
    # Salvar a imagem ja convertida
    cv2.imwrite(new_image_path, transformed_image)
    i = i+1

from glob import glob

multipleImages = glob('Aleatorio1\\*.png')
plt.imshow(cv2.imread(multipleImages[0])[:,:,::-1])

